### ISSUE TITLE
Bug: wrong import in phongrender.

### ISSUE THREAD

**Issue by Arthur151** [NVIDIAGameWorks/kaolin#108]
Thanks for your great effort!
I have noticed that there is a bug in kaolin/graphics/dib_renderer/renderer/phongrender.py
https://github.com/NVIDIAGameWorks/kaolin/blob/ce778280f433836a44f80b2e23d6830c96aed6aa/kaolin/graphics/dib_renderer/renderer/phongrender.py#L26
It should be convert to :
from .fragment_shaders.frag_phongtex import fragmentshader

**Comment by shumash** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and this issue is no longer current.

Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)
