### ISSUE TITLE
Illegal memory access in load_textures

### ISSUE THREAD

**Issue by tejank10** [NVIDIAGameWorks/kaolin#112]
I am trying to load an obj file into TriangleMesh with `with_vt=True`. The mesh contains multiple textures. While the first texture image gets loaded into GPU correctly , I am getting following error for subsequent texture images. The error occurs at [this line](https://github.com/NVIDIAGameWorks/kaolin/blob/ce778280f433836a44f80b2e23d6830c96aed6aa/kaolin/rep/Mesh.py#L489)
```
RuntimeError: CUDA error: an illegal memory access was encountered
```

Specs:
```
pytorch                   1.3.1           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
cudatoolkit               10.1.243             h6bb024c_0  
```
GPU: Titan Xp
Driver Version: 440.33.01
CUDA Version: 10.2,  V10.2.89

**Comment by zhjscut** [comment]
Me too, I encountered the same problem when loading .obj file with textures. It seems because this line:
`textures = load_textures_cuda.load_textures(image, faces, textures, is_update)`
If I replace it with:
`textures = torch.ones([faces.size(0), texture_res ** 2, 3])`
Then it will not cause CUDA error, working normally like when the parameter `load_texture` is set False in `load_obj` function.
Because the function `load_textures_cuda` in module `soft_renderer.cuda` is written in .cpp and .cu file, and I don't know how to make my code call it correctly, so my debugging is interrupted. Anyone can help me?

GPU: GeForce RTX 2080 Ti
CUDA Version: release 10.0, V10.0.130
Pytorch Version: 1.2.0

**Comment by shumash** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and this issue is no longer current.

Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)
