### ISSUE TITLE
setup.py - compilation error

### ISSUE THREAD

**Issue by elcire** [NVIDIAGameWorks/kaolin#135]
python setup.py install 
fails with

5 errors detected in the compilation of "C:/Users/xxxx/AppData/Local/Temp/tmpxft_00006d08_00000000-10_sided_distance_cuda.cpp1.ii".
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin\\nvcc.exe' failed with exit status 1

This is with pytorch 1.4, windows 10, Conda with python 3.6 and CUDA 10.1.

Thanks

**Comment by ChildAdrian** [comment]
Same as you, both pytorch 1.4.0, windows 10 with:
5 errors detected in the compilation of "C:/Users/xxxx/AppData/Local/Temp/tmpxft_000012b8_00000000-10_sided_distance_cuda.cpp1.ii".
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.2\\bin\\nvcc.exe' failed with exit status 1

I consider if it is the 1.4.0 ver of pytorch cause the error?
Because my 5 errors are:

C:/python37/lib/site-packages/torch/include\torch/csrc/jit/argument_spec.h(190): error: member "torch::jit::ArgumentSpecCreator::DEPTH_LIMIT" may not be initialized

C:/python37/lib/site-packages/torch/include\torch/csrc/jit/script/module.h(467): error: member "torch::jit::script::detail::ModulePolicy::all_slots" may not be initialized

C:/python37/lib/site-packages/torch/include\torch/csrc/jit/script/module.h(480): error: member "torch::jit::script::detail::ParameterPolicy::all_slots" may not be initialized

C:/python37/lib/site-packages/torch/include\torch/csrc/jit/script/module.h(494): error: member "torch::jit::script::detail::BufferPolicy::all_slots" may not be initialized

C:/python37/lib/site-packages/torch/include\torch/csrc/jit/script/module.h(507): error: member "torch::jit::script::detail::AttributePolicy::all_slots" may not be initialized

**Comment by LeoYuanjieLi** [comment]
I am getting the same error

**Comment by ChildAdrian** [comment]
https://github.com/facebookresearch/detectron2/issues/9#issuecomment-549013090
could resolve these 5 error. and for pytorch 1.4.0, additionally change 4 "constexpr" into "const" in
/python37/lib/site-packages/torch/include\torch/csrc/jit/script/module.h

**Comment by mdcramer** [comment]
Same here. I was able to fix the `argument_spec.h(190)` error by following https://github.com/facebookresearch/detectron2/issues/9#issuecomment-549013090. It did not, however, resolve the 4 errors (I have exactly the same) with `module.h`.

Update: I found those exact 4 error with `module.h` at https://github.com/rusty1s/pytorch_scatter/issues/110#issuecomment-583991445, and it looks like someone found a solution, but unfortunately I was unable to get that to work. The errors are the same, but perhaps that fix is unrelated to my problem.

Update: https://github.com/rusty1s/pytorch_scatter/blob/master/script/torch.sh is exactly what I need.

**Comment by shumash** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and this issue is no longer current.

Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)
