### ISSUE TITLE
Add differentiable rendering tutorial

### ISSUE THREAD

**Issue by krrish94** [NVIDIAGameWorks/kaolin#230]
https://kaolin.readthedocs.io/en/latest/notes/differentiable_rendering.html

**Comment by shumash** [comment]
The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and this issue is no longer current.

The new DIB-R tutorial is available here:
[examples/tutorial/dibr_tutorial.ipynb](https://github.com/NVIDIAGameWorks/kaolin/blob/master/examples/tutorial/dibr_tutorial.ipynb)
