### ISSUE TITLE
Specify background value to use with DIB VC renderer?

### ISSUE THREAD

**Issue by ebartrum** [NVIDIAGameWorks/kaolin#240]
Is it possible to do as the title says? At the moment, I add the bg value * 1 - the mask. However, this leaves a black ring around the mesh in the output.

**Comment by shumash** [comment]
Sorry we were not able to address this. Closing old issue.

Lots has changes since this was posted. Check out new differentiable rendering functionality for `usd`, `obj`, and `gltf` files in [this tutorial](https://github.com/NVIDIAGameWorks/kaolin/blob/master/examples/tutorial/easy_mesh_render.ipynb).
