### ISSUE TITLE
wrong function call 

### ISSUE THREAD

**Issue by EdwardSmith1884** [NVIDIAGameWorks/kaolin#28]
should be kal.mathutils not kal.math in many instances, 

ex: 
 
https://github.com/NVIDIAGameWorks/kaolin/blob/f858c5821084801d83d3ba829c0f15472f8fd31b/kaolin/datasets/shapenet.py#L317

https://github.com/NVIDIAGameWorks/kaolin/blob/83002fedc67e1c9112a8f834ffb4f8a890e6042a/kaolin/graphics/SoftRenderer.py#L183

https://github.com/NVIDIAGameWorks/kaolin/blob/83002fedc67e1c9112a8f834ffb4f8a890e6042a/kaolin/graphics/SoftRenderer.py#L502

**Comment by krrish94** [comment]
Yes! Needs fixing. Thanks for pointing this out

**Comment by shumash** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and this issue is no longer current. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)
