### ISSUE TITLE
Render normals with DIBRenderer

### ISSUE THREAD

**Issue by ebartrum** [NVIDIAGameWorks/kaolin#283]
Im currently using the DIB VCRenderer. Is there an easy way to use it to render the normals of the mesh?

**Comment by shumash** [comment]
We are addressing old issues, and I am sorry this reply comes so late. The library has since been completely reformatted.

Yes, there is a way to differentiably render normals using either `dib-r` or `nvdiffrast` back end. See [kaolin.render.easy_render.render_mesh](https://kaolin.readthedocs.io/en/latest/modules/kaolin.render.easy_render.mesh.html#kaolin.render.easy_render.mesh.render_mesh) function. You can import and render from `.usd`, `.gltf`, `.obj` formats. The normals are returned as part of the dictionary. Check out new [Mesh Easy Render](https://github.com/NVIDIAGameWorks/kaolin/blob/master/examples/tutorial/easy_mesh_render.ipynb) tutorial.
