### ISSUE TITLE
Artifacts in DIB-R rendered color images

### ISSUE THREAD

**Issue by Mystiking** [NVIDIAGameWorks/kaolin#309]
I've been using the DIB-R [phongrender](https://github.com/NVIDIAGameWorks/kaolin/blob/master/kaolin/graphics/dib_renderer/renderer/phongrender.py) for some time now, and I have noticed that artifacts - black pixels - seem to appear near edges that are perfectly aligned with the camera. See the attached images for some examples.

![color_image_artifacts](https://user-images.githubusercontent.com/8426728/91685801-b20d7880-eb5b-11ea-9b3f-751ed53c389a.png)

![gt_I_sphere](https://user-images.githubusercontent.com/8426728/91685878-eda84280-eb5b-11ea-9028-f16b0ac1d9f9.png)

![gt_I_demo_object](https://user-images.githubusercontent.com/8426728/91685891-f9940480-eb5b-11ea-8b7c-8ddf1c991ea4.png)

I'm not sure if this is an issue in the [rasterizer](https://github.com/NVIDIAGameWorks/kaolin/blob/master/kaolin/graphics/dib_renderer/rasterizer/rasterizer.py) or somewhere else, but I just wanted to let you know.

**Comment by shumash** [comment]
Thank you for your comment. Closing old bug, as the library significantly changes since that time.

If you run into issues with latest version, please post a new bug. An easy way to try differentiable shader is in this tutorial:
[examples/tutorial/easy_mesh_render.ipynb](https://github.com/NVIDIAGameWorks/kaolin/blob/master/examples/tutorial/easy_mesh_render.ipynb)
