### ISSUE TITLE
When will the reformatted branch be released?

### ISSUE THREAD

**Issue by tau-yihouxiang** [NVIDIAGameWorks/kaolin#311]
"A reformat is currently planned on Kaolin, we are expecting the reformat branch to be released in late August. Pull request reviews will be delayed until then." When will the reformatted branch be released?

**Comment by Caenorst** [comment]
We are having some delay but the branch should be there before the end of September.

**Comment by MBrandt-NASA** [comment]
That's great to hear!  Kaolin is great! 😄 .  I successfully implemented my own Dataset (TerrainPointCloudDataset) based off KaolinDataset, your ModelNet Dataset and Shapenet_Points Dataset to read in my own point cloud data based on lunar terrain for a NASA research project I'm working on.  I also adapted my own random upsampling / downsampling based off the Kaolin Transform, etc.

Your PointNetClassifier worked great for me!  I'm looking forward to trying some other models in your Model Zoo.

_Especially I'd love to see some Semantic Segmentation examples_!!

I hope to see development on Kaolin be ongoing -- updated for the latest Python version, etc.

Btw, in my project I followed your Windows 10 build instructions, using Python 3.6 and the latest PyTorch (1.6), with Anaconda and PyCharm on Win 10, and all worked well for me.

Thanks so much for making this great library available and for continuing to develop it and support it!  👍 

I intend to continue using Kaolin on a new NASA project during the coming year.

Here's example output classifying 3 lunar terrain features (craters, cliffs, and plains), based off actual lunar terrain data (SLDEM2013 from the Kaguya (Selene) and LRO missions):

![10_epochs_94_perc_val_acc_91372_samples_cropped](https://user-images.githubusercontent.com/4731852/93692744-c989b280-fac4-11ea-8a67-b3b0255a16cf.png)

**Comment by MBrandt-NASA** [comment]
The PointNet2Classifier was successful on the same dataset, as expected, with 99.34% validatioin accuracy... took (as compared to PointNet) more than twice the training time at 13.9 hrs on a 2080 Ti, full Cuda utilization and dedicated  GPU memory also full.  It got everything correct... so yeah, more accurate than PointNet, as expected:

![PointNet2_10_epochs_99_perc_val_acc_91372_files_cropped](https://user-images.githubusercontent.com/4731852/93721661-b1b33c80-fb5f-11ea-94c2-db45e0751139.png)

It's super awesome to be able to just change 1 line of code to use a new model so easily!  Great job, Kaolin developers!  😃

**Comment by shumash** [comment]
Hi, thank you very much for using Kaolin and your support! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

Unfortunately, that meant removing some of the models that you were using, because we could not vouch that they would continue to work with library updates. We are planning to release the improved model zoo as a separate repository, but cannot comment on the ETA at this time. Please Watch the github repository for updates, and happy training!
