### ISSUE TITLE
kaolin/cython/triangle_hash.pyx' doesn't match any files

### ISSUE THREAD

**Issue by wissalsayhi** [NVIDIAGameWorks/kaolin#32]
I tried installing kaolin on both windows10 and ubuntu 16.04 and in both cases I recieve the same error 
![kaolin_error](https://user-images.githubusercontent.com/13519346/69320024-a9892880-0c40-11ea-8e87-bcda0758f878.JPG)

Any suggestions ?

**Comment by shumash** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and this issue is no longer current. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)
