### ISSUE TITLE
something wrong in '/usr/include/c++/6/tuple' and '/usr/bin/nvcc'

### ISSUE THREAD

**Issue by 96wangfeng** [NVIDIAGameWorks/kaolin#327]
![image](https://user-images.githubusercontent.com/37011205/100616106-8fa21b80-3353-11eb-8836-b09c993f8e4a.png)
I use pytorch=1.2.0 torchvision=0.4.0 cuda=10.0.130, when I use 'python setup.py install', the screenshot is shown in the figure. How to solve this problem?

**Comment by GentleDell** [comment]
Hi,

I encountered the same issue when I tried to set up Kaolin on our server. Almost the same errors as the above image. Finally, I managed to install kaolin on my laptop, though I really need to install it on the server. 

**Server** (fail):
  pytorch = 1.70, 
  torchvision = 1.8.1, 
  cuda = 10.2, 
  python = 3.7.9, 
  numpy = 1.19.2, 

  nvcc --version:
    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2017 NVIDIA Corporation
    Built on Fri_Nov__3_21:07:56_CDT_2017
    Cuda compilation tools, release 9.1, V9.1.85

  most of errors are reported from /usr/include/c++/6/tuple

**My Laptop** (success):
  pytorch = 1.70, 
  torchvision = 1.8.1, 
  cuda = 10.2, 
  python = 3.7.9, 
  numpy = 1.19.4,

  nvcc --version
    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2019 NVIDIA Corporation
    Built on Wed_Oct_23_19:24:38_PDT_2019
    Cuda compilation tools, release 10.2, V10.2.89

  There is only /usr/include/c++/7 on my laptop.

So, would it because of the version of Cuda compilation tools/ C++ version?

Any help would be much appreciated.

**Comment by 96wangfeng** [comment]
I install it using the docker downloaded from the docker hub.

**Comment by shumash** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our [latest documentation](https://kaolin.readthedocs.io/en/latest/), and let us know if the features you need are missing.

Closing this bug as it is no longer current.
