### ISSUE TITLE
DIB_R  Readme.

### ISSUE THREAD

**Issue by shersoni610** [NVIDIAGameWorks/kaolin#47]
Hello,

I was reading the README.md in the folder DIB-R. I am not sure if the description 
is correct or I do not know how to run it. 

Can someone help?

**Comment by shumash** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and this issue is no longer current. 

Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

And to our DIB-R tutorial:
[examples/tutorial/dibr_tutorial.ipynb](https://github.com/NVIDIAGameWorks/kaolin/blob/master/examples/tutorial/dibr_tutorial.ipynb)
