### ISSUE TITLE
May be bug here:should append dim = 0

### ISSUE THREAD

**Issue by YunzhongTianjing** [NVIDIAGameWorks/kaolin#83]
https://github.com/NVIDIAGameWorks/kaolin/blob/6185b20ab9202e703249b1f168fdb1a5eba5c008/kaolin/conversions/meshconversions.py#L80
https://github.com/NVIDIAGameWorks/kaolin/blob/6185b20ab9202e703249b1f168fdb1a5eba5c008/kaolin/conversions/meshconversions.py#L81

Should append dim=0 (to be real bbox), as below:
```python
    if normalize:
        verts_max = mesh.vertices.max(dim = 0).values
        verts_min = mesh.vertices.min(dim = 0).values
```

**Comment by shumash** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and this issue is no longer current. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)
